### ISSUE TITLE
TransformVariables: a subset of optics functionality?

### ISSUE THREAD

**Issue by aplavin** [tpapp/TransformVariables.jl#114]
Looks like all major functionality of `TransformVariables` is available as optics/lenses, as defined in `Accessors`. Optics are very general and composable, so maybe it's worth looking into "replacing" `TransformVariables` usage with optics. If some useful features aren't covered by optics yet, this most likely can be improved.

Simple example along the lines of `TransformVariables` docs:
```julia
julia> using AccessorsExtra, StaticArrays

# @optics may be upstreamed to Accessors proper at some point
julia> o = @optics log(_.μ) log(_.σ) log(_.τ) _.θs[∗]

julia> y = (μ=1, σ=2, τ=3, θs=SVector(4, 5))

julia> getall(y, o)
(0.0, 0.6931471805599453, 1.0986122886681098, 4, 5)

julia> setall(y, o, getall(y, o) .+ 1)
(μ = 2.718281828459045, σ = 5.436563656918091, τ = 8.154845485377137, θs = [5, 6])
```

**Comment by tpapp** [comment]
I consider calculating the log determinant of the Jacobian major functionality, and I am not sure how you would implement that with optics. See `transform_and_logjac`.

Also, a lot of transformations are nonlinear mappings.

Are you sure you read the manual?

**Comment by tpapp** [comment]
See https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant#Jacobian_determinant, https://en.wikipedia.org/wiki/Integration_by_substitution#Substitution_for_multiple_variables, and the docs.

**Comment by tpapp** [comment]
The Jacobian of the result flattened to a vector.

**Comment by tpapp** [comment]
No worries, suggestions are always welcome. Yes, this functionality is very specific to Bayesian estimation / MCMC. I  will close the issue for now as I think it is resolved, but if you comment I will reopen it.
