### ISSUE TITLE
Add ASCII aliases for as* functions

### ISSUE THREAD

**Issue by jlumpe** [tpapp/TransformVariables.jl#37]
The `asℝ`, `asℝ₊`, `asℝ₊`, `as𝕀` are difficult to type because (as far as I know) the "Mathematical Double-Struck Capital R" character and others don't work with the backslash completion in the REPL or in IJulia. It would be nice if these were also aliased as `asR, asRp, asRm, asI` or similar.

**Comment by jarredbarber** [comment]
They do: `\bbR`,  `\bbR\_+`, and `\bbI`, 

(with that said, it took some time to figure this out)

**Comment by tpapp** [comment]
Would mentioning this in the docstrings help?

**Comment by jlumpe** [comment]
Ah! Yeah I think it would help a lot to have this in the documentation.
