### ISSUE TITLE
Probability vectors

### ISSUE THREAD

**Issue by cscherrer** [tpapp/TransformVariables.jl#43]
It would be great to be able to use this library to work with Dirichlet distributions. I have a first crack at a `ProbVector` transform for this purpose in [this gist](https://gist.github.com/cscherrer/6335689689d8b3e651ae2aae953a6944), but there's a lot I don't understand yet about your library. Does this look like it's headed in the right direction? I'm thinking I can use a `CustomTransform` to check the math in the implementation.

**Comment by cscherrer** [comment]
Actually, it might be working close to as-is, just need to check the Jacobian.

**Comment by tpapp** [comment]
@cscherrer: can you be more specific about

> use this library to work with Dirichlet distributions

ie what you want to do, specifically?

If you want to transform to a simplex, that functionality is missing, but I could add it if that is what you need.

**Comment by cscherrer** [comment]
Yes, I need to transform to a simplex. My approach was to adapt your l2 remainder for `UnitVector` to instead use l1 and positives only. Is that how you would go about it, it do you see a better way?

**Comment by tpapp** [comment]
I would just code up whatever is used in the Stan docs.

**Comment by scheidan** [comment]
Thanks for this handy package!

I also have a use case for a simplex transformation. Would you recommend to use the gist from @cscherrer or rather to implement something based on the [Stan documentation](https://mc-stan.org/docs/2_18/reference-manual/simplex-transform-section.html)?

**Comment by tpapp** [comment]
Closed by #56, thanks @scheidan :+1:
