### ISSUE TITLE
dimension mismatch for inverse transformation of nested tuples 

### ISSUE THREAD

**Issue by scheidan** [tpapp/TransformVariables.jl#57]
The `inverse` is not working if a named tuple contains (unnamed) tuples:
```Julia
N = 3
tt = as((
    a = as(Tuple(as(Vector, asℝ₊, 2) for _ in 1:N)),
    b = as(Tuple(UnitVector(n) for n in 1:N)),
))

dimension(tt)  # -> 9

x = tt(randn(dimension(tt)))    # ok

y = inverse(tt, x)
# ERROR: ArgumentError: length(x) == dimension(tt) must hold. Got
# length(x) => 9
# dimension(tt) => 6
``` 
Maybe that's not how this package is intended to be used!

My motivation was that while I could use `as(Vector, as(Vector, asℝ₊, 2), N)` for the the field `a`, I could not construct a `Vector` containing different transformations as in field `b`.

**Comment by tpapp** [comment]
This should work, and this is a bug. Thanks for documenting it, I will investigate and fix it.
