### ISSUE TITLE
Vectorizing scalar transforms?

### ISSUE THREAD

**Issue by tkf** [tpapp/TransformVariables.jl#61]
It would be nice if I can create "vectorized" versions of scalar transforms, maybe using something like `as(Array, as𝕀, 10)` such that

```julia
transform(as(Array, as𝕀, size(xs)...), xs) == transform.(as𝕀, xs)
```

Alternative syntaxes may be

```julia
as(Array, 0..1, 10)  # using IntervalSets: (..)
as(Array, 10, Real 0, 1)
```

Is it in the scope of this package?

**Comment by tpapp** [comment]
I am not sure I understand the question correctly. The following works fine already:
```julia
using TransformVariables
t = as(Array, as𝕀, 10)
x = rand(dimension(t))
t(x)
transform_and_logjac(t, x)
```
Perhaps I should just improve the docs?

**Comment by tkf** [comment]
Thanks, I didn't know it works already.  To be honest it wasn't clear from the docs that it's possible.

**Comment by tkf** [comment]
It's great that even things like `as(Array, as(Array, as𝕀, 3), 2)` work :)
