### ISSUE TITLE
Autodiff with constrained variable with Zygote

### ISSUE THREAD

**Issue by sdewaele** [tpapp/TransformVariables.jl#63]
I am having trouble using DynamicHMC + Zygote on a simple example using a constrained variable. This will work with ForwardDiff, but I am interested in Zygote because of the reverse mode autodiff and its efficiency.

Of course, one solution is that Zygote will be expanded to handle this case properly. The reason for raising the problem here is that perhaps a small adjustment in the logdensity could fix this issue?

```julia
using Parameters,DynamicHMC,LogDensityProblems,TransformVariables,Random
using Zygote

struct AProblem
end
(p::AProblem)(θ) = -θ[1]^2/2
p = AProblem()
trans = as(Vector,as(Real,-1.0,1.0),1)
P = TransformedLogDensity(trans,p)
∇P = ADgradient(:Zygote,P)
results = mcmc_with_warmup(Random.GLOBAL_RNG,∇P,100)

# Output:
# ERROR: LoadError: Need an adjoint for constructor StepRange{Int64,Int64}. Gradient is of type Array{Nothing,1}
# ...
# [19] logdensity at C:\Users\sdwaele\.julia\packages\LogDensityProblems\2UHo5\src\LogDensityProblems.jl:168 [inlined]
# ...
```

**Comment by tpapp** [comment]
Thanks for reporting. This is an issue with TransformVariabes.jl (so I am transferring it), here is the MWE:
```julia
using LogDensityProblems, TransformVariables
import Zygote
struct AProblem end
(p::AProblem)(θ) = -θ[1]^2/2
p = AProblem()
trans = as(Vector,as(Real,-1.0,1.0),1)
P = TransformedLogDensity(trans,p)
∇P = ADgradient(:Zygote,P)
LogDensityProblems.logdensity_and_gradient(∇P, [1.0])
```

I also want to use Zygote, but it cannot AD through a lot of the transformation code. In the past, I would isolate these as issues for Zygote, but I am not sure that's the best way as it remains very fragile (updates to Zygote and/or Julia can break it easily). Once #36 is fixed, I will explore defining adjoints via http://www.juliadiff.org/ChainRules.jl/dev/ which should be a very robust fix.

**Comment by sdewaele** [comment]
Thanks for further reducing the code to the MWE. By the way, definition of a custom adjoint [directly in zygote](https://fluxml.ai/Zygote.jl/latest/adjoints/#Custom-Adjoints-2) is also an option. 

Zygote seems to have some way to go before it can support the much larger variety of code that occurs in probabilistic inference, compared to neural networks. I hope it will get there eventually, or another reverse-mode autodiff package will emerge to support this.

**Comment by hessammehr** [comment]
I think I may have made a bit of progress on this issue:

```julia
# my MWE
t = as(Array, as𝕀, 1)
# point to be transformed
p = [0.0]
_, pb = pullback(t, p)
# this gives the missing adjoint error
pb(1.0)
```

By defining the adjoint
```julia
Zygote.@adjoint StepRange{Int64, Int64}(a::Int64, b::Int64) = a:b, Δ -> (nothing, nothing)
Zygote.@adjoint StepRange{Int64, Int64}(a::Int64, b::Int64, c::Int64) = a:b:c, Δ -> (nothing, nothing, nothing)
```

`pb(1.0)` works without issue now. Sadly, generalizing this to more than one dimension gives a different error:

```julia
t = as(Array, as𝕀, 2)
p = [0.0, 0.0]

_,pb = pullback(t, p)
pb(1.0)
# MethodError: no method matching reducedim_init(::typeof(identity), ::typeof(Zygote.accum), ::Array{Tuple{Float64,Nothing},1}, ::Tuple{Int64})
```

I would like to dig deeper and find out how we get here, although I wonder if you've already tried all this.

**Comment by sdewaele** [comment]
Thanks for looking into this! I have not tried this, but I am still interested in a fix.

**Comment by hessammehr** [comment]
@sdewaele https://github.com/JuliaLang/julia/issues/31427 seems to be the underlying issue. Perhaps @MikeInnes could propose a workaround in the mean time?

**Comment by sdewaele** [comment]
Good to know that other people have encountered the same issue, that increases the chances that it will be fixed!

**Comment by hessammehr** [comment]
Correction, it seems like with the two adjoints above defined — I just had the wrong input to `pullback` before!

```julia
using Zygote
using TransformVariables
Zygote.@adjoint StepRange{Int64, Int64}(a::Int64, b::Int64) = a:b, Δ -> (nothing, nothing)
Zygote.@adjoint StepRange{Int64, Int64}(a::Int64, b::Int64, c::Int64) = a:b:c, Δ -> (nothing, nothing, nothing)

t = as(Array, as𝕀, 2)
pullback(t, [1.0, 2.0])[2]([1.0, 1.0])
# ([0.19661193324148188, 0.1049935854035065],)
```

@tpapp Your MWE also seems to work correctly now.
```julia
using LogDensityProblems, TransformVariables
import Zygote
Zygote.@adjoint StepRange{Int64, Int64}(a::Int64, b::Int64) = a:b, Δ -> (nothing, nothing)
Zygote.@adjoint StepRange{Int64, Int64}(a::Int64, b::Int64, c::Int64) = a:b:c, Δ -> (nothing, nothing, nothing)
struct AProblem end
(p::AProblem)(θ) = -θ[1]^2/2
p = AProblem()
trans = as(Vector,as(Real,-1.0,1.0),1)
P = TransformedLogDensity(trans,p)
∇P = ADgradient(:Zygote,P)
LogDensityProblems.logdensity_and_gradient(∇P, [1.0])
# (-1.0401523279935367, [-0.6438326526059065])
∇P = ADgradient(:Zygote,P)

LogDensityProblems.logdensity_and_gradient(∇P, [1.0])
# (-1.0401523279935367, [-0.6438326526059065])
```

**Comment by sdewaele** [comment]
Thanks a lot, @hessammehr ! This enables using `Zygote`+`TransformVariables` as intended.
