### ISSUE TITLE
transform of asℝ₊ variable turns Float32 into Float64

### ISSUE THREAD

**Issue by jonalm** [tpapp/TransformVariables.jl#84]
Don't know if this is considered a bug, but I see the following behavior:

```julia
> t = as((; α = asℝ₊, β = asℝ ))
> typeof(transform(t)(Float32[1,2]))
NamedTuple{(:α, :β), Tuple{Float64, Float32}}
```
I was expecting both values to be of Float32 type.

**Comment by tpapp** [comment]
Thanks for the bug report, this was unintended and should be fixed now.
